# CLEAN
- name: "Starting the step CLEAN."
  include_tasks: steps/0_clean.yml
  vars: 
    cleanme: "{{ cleanme | default({}) }}"
  when: "{{ cleanme.condition | default(True) }}"
  with_items: "{{ step_values.clean }}"
  loop_control: { loop_var: cleanme }

# DOWNLOAD
- name: "Starting the step DOWNLOAD."
  include_tasks: steps/1_download.yml
  vars:
    download: "{{ download | default({}) }}"
  when: "{{ download.condition | default(True) }}"
  with_items: "{{ step_values.downloads }}"
  loop_control: { loop_var: download }

# IMPORTS
- name: "Starting the step IMPORTS."
  include_tasks: steps/2_import.yml
  vars:
    importedfile: "{{ importedfile | default({}) }}"
  when: "{{ importedfile.condition | default(True) }}"
  with_items: "{{ step_values.imports }}"
  loop_control: { loop_var: importedfile }

# SHORTCURTS
- name: "Starting the step SHORTCURTS."
  include_tasks: steps/3_shortcut.yml
  vars:
    shortcutlnk: "{{ shortcuts | default({}) }}"
  when: "{{ shortcuts.condition | default(True) }}"
  with_items: "{{ step_values.imports }}"
  loop_control: { loop_var: shortcuts }