- name: Set default values
  set_fact:
    delete_path: "{{ job_values.path          | default('') }}"
    delete_ignore_errors: "{{ job_values.path | default(False) }}"

- debug:
    msg: 
    - "{{ delete_path }}"
    - "{{ delete_ignore_errors }}" 

- name: Windows
  block:
    - name: Getting files/directories status
      win_stat:
        path: "{{ delete_path }}"
      register: reg_delete_path

    - name: "Cleaning specified file."
      win_file:
        path: "{{ delete_path }}"
        state: absent
      ignore_errors: "{{ delete_ignore_errors }}"
      when: reg_delete_path.stat.exists
  when: '"windows" in ansible_system|lower'