# ansible-playbook playbook-demo.yml -i localhost
- name: Common windows tasks executer
  hosts: localhost
  tasks:
    - name: Install Demo
      include_tasks: tasks/main.yml
      vars: { product: 'demo', extras: { chocolatey: { name: thisisanextra, 
                                                       pinned: False, 
                                                       state: present, 
                                                       timeout: 666, 
                                                       version: "69.0.0"} } }


