# Loops through the specified instructions from the var file.

- name: Starting the phases.
  include_tasks: "modules/{{ current_job.key }}/main.yml"
  vars: { job_values: "{{ current_job.value | default({}) }}" }
  with_dict: "{{ jobs.jobs }}"
  loop_control: { loop_var: current_job }