- debug:
      msg: 
      - "{{ rule.name }}" 
      - "{{ rule.localport | default('any') }}"
      - "{{ rule.action    | default('allow') }}" 
      - "{{ rule.direction | default('in') }}" 
      - "{{ rule.protocol  | default('any') }}" 
      - "{{ rule.state     | default('present') }}" 
      - "{{ rule.enabled   | default('True') }}" 
      - "{{ rule.program   | default('any') }}"

# - name: Adding firewall rule
#   community.windows.win_firewall_rule:
#     name: "{{ rule.name }}"
#     localport: "{{ rule.localport | default('any') }}"
#     action: "{{ rule.action       | default('allow') }}"
#     direction: "{{ rule.direction | default('in') }}"
#     protocol: "{{ rule.protocol   | default('any') }}"
#     program: "{{ rule.program     | default('any') }}"
#     state: "{{ rule.state         | default('present') }}"
#     enabled: "{{ rule.enabled     | default('True') }}"
