- name: "Starting the step WINDOWS REGISTRIES EDITION."
  include_tasks: steps/0_regedits.yml
  vars:
    registry: "{{ winreg | default({}) }}"
  when: "{{ winreg.condition | default(True) }}"
  with_items: "{{ step_values.regedits }}"
  loop_control: { loop_var: winreg }

- name: "Starting the step WINDOWS SERVICES."
  include_tasks: steps/1_services.yml
  vars:
    service: "{{ winservice | default({}) }}"
  when: "{{ winservice.condition | default(True) }}"
  with_items: "{{ step_values.services }}"
  loop_control: { loop_var: winservice }