# CHOCOLATEY
- name: "Starting the step CHOCOLATEY."
  include_tasks: steps/0_chocolatey.yml
  vars: 
    package: "{{ chocolatey_package | default({}) }}"
  when: "{{ chocolatey_package.condition | default(True) }}"
  with_items: "{{ step_values.chocolatey }}"
  loop_control: { loop_var: chocolatey_package }

# FEATURES
- name: "Starting the step FEATURES."
  include_tasks: steps/1_features.yml
  vars: 
    feature: "{{ l_feature | default({}) }}"
  when: "{{ feature.condition | default(True) }}"
  with_items: "{{ step_values.features }}"
  loop_control: { loop_var: l_feature }

# EXECUTABLES
- name: "Starting the step EXECUTABLES."
  include_tasks: steps/2_executables.yml
  vars:
    executable: "{{ l_executable | default({}) }}"
  when: "{{ executable.condition | default(True) }}"
  with_items: "{{ step_values.executables }}"
  loop_control: { loop_var: l_executable }

# REBOOT THE SYSTEM IF reboot_after is `True`
- name: Reboot a slow machine that might have lots of updates to apply
  win_reboot:
    reboot_timeout: 3600
    post_reboot_delay: 120
  when: "{{ step_values.reboot_after | default(False) }}"