# stats
- debug:
    msg: 
    - "{{ file_path }}" 
    - "{{ register_name }}"

#- name: Getting files/directories status
#  ansible.windows.win_stat:
#    path: "{{ file_path }}"
#  register: "{{ register_name }}"