- name: Set default values
  set_fact:
    chocolatey_name: "{{ job_values.name                   | default(None) }}" 
    chocolatey_state: "{{ job_values.state                 | default('latest') }}" 
    chocolatey_version: "{{ job_values.version             | default(None) }}"
    chocolatey_timeout: "{{ job_values.timeout             | default(2700) }}"
    chocolatey_pinned: "{{ job_values.pinned               | default(False) }}"
    chocolatey_choco_args: "{{ job_values.choco_args       | default([]) }}"
    chocolatey_install_args: "{{ job_values.install_args   | default('') }}"
    chocolatey_ignore_errors: "{{ job_values.ignore_errors | default(False) }}"

- debug:
    msg: 
    - "{{ chocolatey_name }}" 
    - "{{ chocolatey_version }}" 
    - "{{ chocolatey_state }}"
    - "{{ chocolatey_timeout }}"
    - "{{ chocolatey_pinned }}"
    - "{{ chocolatey_choco_args }}"
    - "{{ chocolatey_install_args }}"
    - "{{ chocolatey_ignore_errors }}"

- name: Windows
  block:
    - name: Install / Upgrade the Chocolatey chocolatey
      win_chocolatey:
        name: "{{ chocolatey_name }}"
        state: "{{ chocolatey_state }}"
        version: "{{ chocolatey_version }}"
        timeout: "{{ chocolatey_timeout }}"
        pinned: "{{ chocolatey_pinned }}"
        choco_args: "{{ chocolatey_choco_args }}"
        install_args: "{{ chocolatey_install_args }}"
      ignore_errors: "{{ chocolatey_ignore_errors }}"
  when: '"windows" in ansible_system|lower'