- name: Set default values
  set_fact:
    download_url: "{{ job_values.url | default('undefined') }}" 
    download_destination: "{{ job_values.destination | default(playbook_dir) }}" 
    download_force: "{{ job_values.force | default(False) }}" 
    download_archive_destination: "{{ job_values.archive.destination | default('undefined') }}"

- debug:
    msg: 
    - "{{ download_url }}" 
    - "{{ download_destination }}" 
    - "{{ download_force }}" 
    - "{{ download_archive_destination }}"

- name: Windows
  block:
    - name: Download the specified file from the URL.
      win_get_url:
        url: "{{ download_url }}"
        dest: "{{ download_destination }}"
        force: "{{ download_force }}"
      when: download.archive.destination != 'undefined'

    - name: Ensure that the archive before trying to extract its content
      win_stat:
        path: "{{ download_destination }}"
      register: "stat_downloaded_archive"      

    - name: Recursively decompress GZ files in ApplicationLogs.zip
      win_unzip:
        src: "{{ download_destination }}"
        dest: "{{ download_archive_destination }}"
        # recurse: yes
        # delete_archive: yes
      when: download_archive_destination != 'undefined' and stat_downloaded_archive.stat.exists
  when: '"windows" in ansible_system|lower'