# CLEAN
- name: "Starting the step CLEAN."
  include_tasks: steps/0_clean.yml
  vars: 
    clean_path: "{{ cleanme.path }}"
  when: "{{ cleanme.condition | default(True) }}"
  loop: "{{ step_values.clean }}"
  loop_control: { loop_var: cleanme }

# DOWNLOAD
- name: "Starting the step DOWNLOAD."
  include_tasks: steps/1_download.yml
  vars:
    download:
      url: "{{ download.url }}"
      destination: "{{ download.destination }}"
      force: "{{ download.force | default(False) }}"
      archive:
        archive: "{{ download.archive.archive | False }}"
        destination: "{{ download.archive.destination | default('undefined') }}"
  when: "{{ download.condition | default(True) }}"
  loop: "{{ step_values.downloads }}"
  loop_control: { loop_var: download }