# CLEAN
- name: "Starting the step CLEAN."
  include_tasks: steps/0_clean.yml
  vars: 
    clean_path: "{{ cleanme.path }}"
  when: "{{ cleanme.condition | default(True) }}"
  with_items: "{{ step_values.clean }}"
  loop_control: { loop_var: cleanme }

# DOWNLOAD
- name: "Starting the step DOWNLOAD."
  include_tasks: steps/1_download.yml
  vars:
    download:
      url: "{{ download.url }}"
      destination: "{{ download.destination }}"
      force: "{{ download.force }}"
      archive:
        archive: "{{ download.archive.archive }}"
        destination: "{{ download.archive.destination }}"
  when: "{{ download.condition | default(True) }}"
  with_items: "{{ step_values.downloads }}"
  loop_control: { loop_var: download }

# IMPORTS
- name: "Starting the step IMPORTS."
  include_tasks: steps/2_import.yml
  vars:
    importedfile:
      source: "{{ importedfile.source }}"
      destination: "{{ importedfile.destination }}"
      owner: "{{ importedfile.owner }}"
      group: "{{ importedfile.group }}"
      mode: "{{ importedfile.mode }}"
      force: "{{ importedfile.force | default(True) }}"
      template:
        vars: "{{ importedfile.template.vars | default({}) }}"
  when: "{{ importedfile.condition | default(True) }}"
  with_items: "{{ step_values.imports }}"
  loop_control: { loop_var: importedfile }

# SHORTCURTS
- name: "Starting the step SHORTCURTS."
  include_tasks: steps/3_shortcut.yml
  vars:
    shortcutlnk:
      source: "{{ shortcuts.source }}"
      destination: "{{ shortcuts.destination }}"
  when: "{{ shortcuts.condition | default(True) }}"
  with_items: "{{ step_values.imports }}"
  loop_control: { loop_var: shortcuts }