# CLEAN
- name: "Starting the step CLEAN."
  include_tasks: steps/0_clean.yml
  vars: 
    clean_path: "{{ cleanme.path }}"
  when: "{{ cleanme.condition | default(True) }}"
  loop: "{{ step_values.clean }}"
  loop_control: { loop_var: cleanme }

# DOWNLOAD
- name: "Starting the step DOWNLOAD."
  include_tasks: steps/1_download.yml
  vars:
    download:
      url: "{{ download.url }}"
      destination: "{{ download.destination }}"
      force: "{{ download.force }}"
      archive:
        archive: "{{ download.archive.archive }}"
        destination: "{{ download.archive.destination }}"
  when: "{{ download.condition | default(True) }}"
  loop: "{{ step_values.downloads }}"
  loop_control: { loop_var: download }

# IMPORTS
- name: "Starting the step IMPORTS."
  include_tasks: steps/2_imports.yml
  vars:
    import:
      source: "{{ import.source }}"
      destination: "{{ import.destination }}"
      owner: "{{ import.owner }}"
      group: "{{ import.group }}"
      mode: "{{ import.mode }}"
      force: "{{ import.force | default(True) }}"
  when: "{{ import.condition | default(True) }}"
  loop: "{{ step_values.imports }}"
  loop_control: { loop_var: import }